services:
  - type: web
    name: fastapi-api
    runtime: docker
    plan: free
    region: oregon
    dockerCommand: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_CAPACITY
        value: 60
      - key: RATE_LIMIT_REFILL_RATE
        value: 1

databases:
  - name: fastapi-db
    plan: free
    region: oregon
    postgresMajorVersion: "17"
    databaseName: fastapi
    user: fastapi_user
